In [35]:
import numpy as np
a=np.array([3,3,3,4,])

a.mean()


3.25

In [7]:
type(a)

numpy.ndarray

In [8]:
len(a)

4

In [9]:
a[0000]

3

In [10]:
a[0]

3

In [12]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
c=np.zeros(5)
c

array([0., 0., 0., 0., 0.])

In [15]:
d=np.ones(8)

In [16]:
d

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
e=np.empty(3)

In [18]:
e

array([ 9.83024655e-312,  0.00000000e+000, -4.94065646e-324])

In [21]:
f=np.arange(7,9)
f

array([7, 8])

In [22]:
g=np.arange(2,20,2)
g


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
h=np.ones(5,dtype=np.int8)
h

array([1, 1, 1, 1, 1], dtype=int8)

In [26]:
i=np.ones(5,dtype=np.float64)
i

array([1., 1., 1., 1., 1.])

In [31]:
j=np.arange(24).reshape(2,3,4)
j

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [36]:
l=np.array([1,2,3,4,1.2,3,.0,45,])
l

array([ 1. ,  2. ,  3. ,  4. ,  1.2,  3. ,  0. , 45. ])

In [37]:
l.sort()

In [38]:
l

array([ 0. ,  1. ,  1.2,  2. ,  3. ,  3. ,  4. , 45. ])

In [39]:
m=np.array([4,23,5,223,.342,23,23])
m

array([  4.   ,  23.   ,   5.   , 223.   ,   0.342,  23.   ,  23.   ])

In [40]:
m.sort()
m

array([  0.342,   4.   ,   5.   ,  23.   ,  23.   ,  23.   , 223.   ])

In [42]:
np.concatenate((l,m))

array([  0.   ,   1.   ,   1.2  ,   2.   ,   3.   ,   3.   ,   4.   ,
        45.   ,   0.342,   4.   ,   5.   ,  23.   ,  23.   ,  23.   ,
       223.   ])

In [52]:
n=np.array([[1,2],[7,6]])
n

array([[1, 2],
       [7, 6]])

In [53]:
o=np.array([[2,3],[3,2]])
o

array([[2, 3],
       [3, 2]])

In [54]:
p=np.concatenate((n,o),axis=0)
p

array([[1, 2],
       [7, 6],
       [2, 3],
       [3, 2]])

In [55]:
p.ndim

2

In [56]:
p.size

8

In [57]:
p.shape

(4, 2)

In [66]:
q=np.arange(9)
q

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
t=q.reshape(3,3)
t

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])